/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MatchResult {
  'team1' : Team,
  'team2' : Team,
  'venue' : string,
  'date' : string,
  'score1' : bigint,
  'score2' : bigint,
  'winner' : Team,
}
export interface Photo {
  'url' : string,
  'match' : string,
  'title' : string,
  'description' : string,
}
export interface Player {
  'name' : string,
  'role' : PlayerRole,
  'team' : Team,
  'stats' : PlayerStats,
}
export type PlayerRole = { 'allRounder' : null } |
  { 'bowler' : null } |
  { 'wicketKeeper' : null } |
  { 'batsman' : null };
export interface PlayerStats {
  'runs' : bigint,
  'average' : number,
  'matches' : bigint,
  'wickets' : bigint,
}
export type Team = string;
export interface VideoHighlight {
  'url' : string,
  'title' : string,
  'duration' : string,
  'thumbnail' : string,
  'views' : bigint,
  'description' : string,
}
export interface _SERVICE {
  'addOrUpdateMatch' : ActorMethod<[MatchResult], undefined>,
  'addOrUpdatePhoto' : ActorMethod<[Photo], undefined>,
  'addOrUpdateTopPerformer' : ActorMethod<[Player], undefined>,
  'addOrUpdateVideoHighlight' : ActorMethod<[VideoHighlight], undefined>,
  'getAllMatchResults' : ActorMethod<[], Array<MatchResult>>,
  'getAllPhotos' : ActorMethod<[], Array<Photo>>,
  'getAllTopPerformers' : ActorMethod<[], Array<Player>>,
  'getAllVideoHighlights' : ActorMethod<[], Array<VideoHighlight>>,
  'getMatchById' : ActorMethod<[bigint], [] | [MatchResult]>,
  'getPhotoById' : ActorMethod<[bigint], [] | [Photo]>,
  'getTopPerformerById' : ActorMethod<[bigint], [] | [Player]>,
  'getVideoHighlightById' : ActorMethod<[bigint], [] | [VideoHighlight]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];