/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Team = IDL.Text;
export const MatchResult = IDL.Record({
  'team1' : Team,
  'team2' : Team,
  'venue' : IDL.Text,
  'date' : IDL.Text,
  'score1' : IDL.Nat,
  'score2' : IDL.Nat,
  'winner' : Team,
});
export const Photo = IDL.Record({
  'url' : IDL.Text,
  'match' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const PlayerRole = IDL.Variant({
  'allRounder' : IDL.Null,
  'bowler' : IDL.Null,
  'wicketKeeper' : IDL.Null,
  'batsman' : IDL.Null,
});
export const PlayerStats = IDL.Record({
  'runs' : IDL.Nat,
  'average' : IDL.Float64,
  'matches' : IDL.Nat,
  'wickets' : IDL.Nat,
});
export const Player = IDL.Record({
  'name' : IDL.Text,
  'role' : PlayerRole,
  'team' : Team,
  'stats' : PlayerStats,
});
export const VideoHighlight = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'thumbnail' : IDL.Text,
  'views' : IDL.Nat,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addOrUpdateMatch' : IDL.Func([MatchResult], [], []),
  'addOrUpdatePhoto' : IDL.Func([Photo], [], []),
  'addOrUpdateTopPerformer' : IDL.Func([Player], [], []),
  'addOrUpdateVideoHighlight' : IDL.Func([VideoHighlight], [], []),
  'getAllMatchResults' : IDL.Func([], [IDL.Vec(MatchResult)], ['query']),
  'getAllPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
  'getAllTopPerformers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getAllVideoHighlights' : IDL.Func([], [IDL.Vec(VideoHighlight)], ['query']),
  'getMatchById' : IDL.Func([IDL.Nat], [IDL.Opt(MatchResult)], ['query']),
  'getPhotoById' : IDL.Func([IDL.Nat], [IDL.Opt(Photo)], ['query']),
  'getTopPerformerById' : IDL.Func([IDL.Nat], [IDL.Opt(Player)], ['query']),
  'getVideoHighlightById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(VideoHighlight)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Team = IDL.Text;
  const MatchResult = IDL.Record({
    'team1' : Team,
    'team2' : Team,
    'venue' : IDL.Text,
    'date' : IDL.Text,
    'score1' : IDL.Nat,
    'score2' : IDL.Nat,
    'winner' : Team,
  });
  const Photo = IDL.Record({
    'url' : IDL.Text,
    'match' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const PlayerRole = IDL.Variant({
    'allRounder' : IDL.Null,
    'bowler' : IDL.Null,
    'wicketKeeper' : IDL.Null,
    'batsman' : IDL.Null,
  });
  const PlayerStats = IDL.Record({
    'runs' : IDL.Nat,
    'average' : IDL.Float64,
    'matches' : IDL.Nat,
    'wickets' : IDL.Nat,
  });
  const Player = IDL.Record({
    'name' : IDL.Text,
    'role' : PlayerRole,
    'team' : Team,
    'stats' : PlayerStats,
  });
  const VideoHighlight = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'thumbnail' : IDL.Text,
    'views' : IDL.Nat,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addOrUpdateMatch' : IDL.Func([MatchResult], [], []),
    'addOrUpdatePhoto' : IDL.Func([Photo], [], []),
    'addOrUpdateTopPerformer' : IDL.Func([Player], [], []),
    'addOrUpdateVideoHighlight' : IDL.Func([VideoHighlight], [], []),
    'getAllMatchResults' : IDL.Func([], [IDL.Vec(MatchResult)], ['query']),
    'getAllPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
    'getAllTopPerformers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getAllVideoHighlights' : IDL.Func(
        [],
        [IDL.Vec(VideoHighlight)],
        ['query'],
      ),
    'getMatchById' : IDL.Func([IDL.Nat], [IDL.Opt(MatchResult)], ['query']),
    'getPhotoById' : IDL.Func([IDL.Nat], [IDL.Opt(Photo)], ['query']),
    'getTopPerformerById' : IDL.Func([IDL.Nat], [IDL.Opt(Player)], ['query']),
    'getVideoHighlightById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(VideoHighlight)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };