/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    name: string;
    role: PlayerRole;
    team: Team;
    stats: PlayerStats;
}
export type Team = string;
export interface VideoHighlight {
    url: string;
    title: string;
    duration: string;
    thumbnail: string;
    views: bigint;
    description: string;
}
export interface MatchResult {
    team1: Team;
    team2: Team;
    venue: string;
    date: string;
    score1: bigint;
    score2: bigint;
    winner: Team;
}
export interface PlayerStats {
    runs: bigint;
    average: number;
    matches: bigint;
    wickets: bigint;
}
export interface Photo {
    url: string;
    match: string;
    title: string;
    description: string;
}
export enum PlayerRole {
    allRounder = "allRounder",
    bowler = "bowler",
    wicketKeeper = "wicketKeeper",
    batsman = "batsman"
}
export interface backendInterface {
    addOrUpdateMatch(match: MatchResult): Promise<void>;
    addOrUpdatePhoto(photo: Photo): Promise<void>;
    addOrUpdateTopPerformer(player: Player): Promise<void>;
    addOrUpdateVideoHighlight(highlight: VideoHighlight): Promise<void>;
    getAllMatchResults(): Promise<Array<MatchResult>>;
    getAllPhotos(): Promise<Array<Photo>>;
    getAllTopPerformers(): Promise<Array<Player>>;
    getAllVideoHighlights(): Promise<Array<VideoHighlight>>;
    getMatchById(id: bigint): Promise<MatchResult | null>;
    getPhotoById(id: bigint): Promise<Photo | null>;
    getTopPerformerById(id: bigint): Promise<Player | null>;
    getVideoHighlightById(id: bigint): Promise<VideoHighlight | null>;
}
import type { MatchResult as _MatchResult, Photo as _Photo, Player as _Player, PlayerRole as _PlayerRole, PlayerStats as _PlayerStats, Team as _Team, VideoHighlight as _VideoHighlight } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addOrUpdateMatch(arg0: MatchResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateMatch(arg0);
            return result;
        }
    }
    async addOrUpdatePhoto(arg0: Photo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdatePhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdatePhoto(arg0);
            return result;
        }
    }
    async addOrUpdateTopPerformer(arg0: Player): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateTopPerformer(to_candid_Player_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateTopPerformer(to_candid_Player_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addOrUpdateVideoHighlight(arg0: VideoHighlight): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateVideoHighlight(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateVideoHighlight(arg0);
            return result;
        }
    }
    async getAllMatchResults(): Promise<Array<MatchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatchResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatchResults();
            return result;
        }
    }
    async getAllPhotos(): Promise<Array<Photo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPhotos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPhotos();
            return result;
        }
    }
    async getAllTopPerformers(): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTopPerformers();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTopPerformers();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVideoHighlights(): Promise<Array<VideoHighlight>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideoHighlights();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideoHighlights();
            return result;
        }
    }
    async getMatchById(arg0: bigint): Promise<MatchResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchById(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchById(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhotoById(arg0: bigint): Promise<Photo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotoById(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotoById(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopPerformerById(arg0: bigint): Promise<Player | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopPerformerById(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopPerformerById(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoHighlightById(arg0: bigint): Promise<VideoHighlight | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoHighlightById(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoHighlightById(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_PlayerRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerRole): PlayerRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatchResult]): MatchResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Photo]): Photo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Player]): Player | null {
    return value.length === 0 ? null : from_candid_Player_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoHighlight]): VideoHighlight | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _PlayerRole;
    team: _Team;
    stats: _PlayerStats;
}): {
    name: string;
    role: PlayerRole;
    team: Team;
    stats: PlayerStats;
} {
    return {
        name: value.name,
        role: from_candid_PlayerRole_n8(_uploadFile, _downloadFile, value.role),
        team: value.team,
        stats: value.stats
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    allRounder: null;
} | {
    bowler: null;
} | {
    wicketKeeper: null;
} | {
    batsman: null;
}): PlayerRole {
    return "allRounder" in value ? PlayerRole.allRounder : "bowler" in value ? PlayerRole.bowler : "wicketKeeper" in value ? PlayerRole.wicketKeeper : "batsman" in value ? PlayerRole.batsman : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n6(_uploadFile, _downloadFile, x));
}
function to_candid_PlayerRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerRole): _PlayerRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Player_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Player): _Player {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: PlayerRole;
    team: Team;
    stats: PlayerStats;
}): {
    name: string;
    role: _PlayerRole;
    team: _Team;
    stats: _PlayerStats;
} {
    return {
        name: value.name,
        role: to_candid_PlayerRole_n3(_uploadFile, _downloadFile, value.role),
        team: value.team,
        stats: value.stats
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerRole): {
    allRounder: null;
} | {
    bowler: null;
} | {
    wicketKeeper: null;
} | {
    batsman: null;
} {
    return value == PlayerRole.allRounder ? {
        allRounder: null
    } : value == PlayerRole.bowler ? {
        bowler: null
    } : value == PlayerRole.wicketKeeper ? {
        wicketKeeper: null
    } : value == PlayerRole.batsman ? {
        batsman: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
